# Site settings
title: Antonio Piccolboni
email: antonio@piccolboni.info
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://piccolboni.info" # the base hostname & protocol for your site
twitter_username: piccolbo
github_username:  piccolbo
permalink: /:year/:month/:title.html

plugins:
  - jekyll-sitemap
