# Site settings
title: Antonio Piccolboni
email: antonio@piccolboni.info
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://piccolboni.info" # the base hostname & protocol for your site
twitter_username: piccolbo
github_username:  piccolbo
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown

#excerpt

excerpt_separator: '<!-- more -->'

gems:
  - jekyll-archives
#  - jekyll-feed

# Archives, still need work

jekyll-archives:
  enabled: 'year'
  layouts:
    year: year-archive
  permalinks:
    year: '/:year/'

# attempt to integrate nodebb
#webserver_headers:
#  "Access-Control-Allow-Origin": "*.piccolboni.info"

#feed

# feed:
#   path: atom.xml
